language: rust
rust:
  - 1.24.0
  - 1.25.0
  - 1.26.0
  - 1.27.0
  - 1.28.0
  - 1.29.0
  - 1.30.0
#  - stable
#  - beta
#  - nightly

env:
  - ARCH=x86_64 FEATURES=''
#  - ARCH=i686 FEATURES=''
#  - ARCH=x86_64 FEATURES='serde1'
#  - ARCH=i686 FEATURES='serde1'

addons:
  apt:
    packages:
      - gcc-multilib

script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"
