language: rust
rust:
  - stable
  - beta
  - nightly

env:
  - ARCH=x86_64 FEATURES=''
  - ARCH=i686 FEATURES=''
  - ARCH=x86_64 FEATURES='serde1'
  - ARCH=i686 FEATURES='serde1'

addons:
  apt:
    packages:
      - gcc-multilib

script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"
