[package]
authors = ["Vinzent Steinberg <Vinzent.Steinberg@gmail.com>"]
name = "average"
version = "0.5.0"
license = "MIT/Apache-2.0"
repository = "https://github.com/vks/average"
description = "Calculate the average of a sequence and its error iteratively"
readme = "README.md"
categories = ["science", "no-std"]
keywords = ["statistics", "stats"]

[dependencies]
conv = "0.3"
quickersort = "2"

[dev-dependencies]
bencher = "0.1"
rand = "0.3"
streaming-stats = "0.1"

[[bench]]
name = "average"
harness = false

[[bench]]
name = "min"
harness = false
