[package]
authors = ["Vinzent Steinberg <Vinzent.Steinberg@gmail.com>"]
categories = ["science", "no-std"]
description = "Calculate statistics iteratively"
documentation = "https://docs.rs/average"
keywords = ["stats", "mean", "skewness", "kurtosis", "quantile"]
license = "MIT/Apache-2.0"
name = "average"
readme = "README.md"
repository = "https://github.com/vks/average"
version = "0.9.2"

[features]
serde1 = ["serde", "serde_derive"]

[[bench]]
harness = false
name = "mean"

[[bench]]
harness = false
name = "min"

[[bench]]
harness = false
name = "kurtosis"

[dependencies]
num-traits = "0.2"
num-integer = "0.1"
float-ord = "0.2"
serde = { version = "1", optional = true }
serde_derive = { version = "1", optional = true }

[dependencies.conv]
default-features = false
version = "0.3"

[dev-dependencies]
bencher = "0.1"
rand = "0.5"
serde_json = "1"
streaming-stats = "0.2"
quantiles = "0.7"
