[package]
authors = ["Vinzent Steinberg <Vinzent.Steinberg@gmail.com>"]
name = "average"
version = "0.1.0"
license = "MIT/Apache-2.0"
repository = "https://github.com/vks/average"
description = "Calculate the average of a sequence iteratively"
keywords = ["statistics", "stats"]
categories = ["science", "no-std"]

[dependencies]
conv = "0.3"
