[package]
authors = ["Vinzent Steinberg <Vinzent.Steinberg@gmail.com>"]
categories = ["science", "no-std"]
description = "Calculate the average of a sequence and its error iteratively"
keywords = ["statistics", "stats"]
license = "MIT/Apache-2.0"
name = "average"
repository = "https://github.com/vks/average"
version = "0.1.0"

[dependencies]
conv = "0.3"

[dev-dependencies]
rand = "0.3"
