[package]
authors = ["Vinzent Steinberg <Vinzent.Steinberg@gmail.com>"]
categories = ["science", "no-std"]
description = "Calculate statistics iteratively"
documentation = "https://docs.rs/average"
keywords = ["stats", "mean", "skewness", "kurtosis", "quantile"]
license = "MIT/Apache-2.0"
name = "average"
readme = "README.md"
repository = "https://github.com/vks/average"
version = "0.7.0"

[[bench]]
harness = false
name = "mean"

[[bench]]
harness = false
name = "min"

[[bench]]
harness = false
name = "kurtosis"

[dependencies]
num-traits = "0.2"
num-integer = "0.1"
quickersort = "3"

[dependencies.conv]
default-features = false
version = "0.3"

[dependencies.serde]
features = ["derive"]
optional = true
version = "1"

[dev-dependencies]
bencher = "0.1"
rand = "0.5"
serde_json = "1"
streaming-stats = "0.2"
